### ISSUE TITLE
Issue with the batch mode test

### ISSUE THREAD

**Issue by mengxiao-he** [yunguan-wang/SPROD#30]
Hi,

Thanks for the software.

I'm having some issues with the batch mode test that i was hoping to get some help with.

```
Removing previous testing results...Done! 
Testing Sprod in single mode
Sprod test single mode succeeded!
Testing Sprod in batch mode
Sprod denoise job failed: no output found, please check sprod_log.txt.
Testing Sprod in single, pseudoimage mode
Starting dirichlet process clustering...
Iteration 10 
Iteration 20 
Iteration 30 
Iteration 40 
Iteration 50 
Iteration 60 
Iteration 70 
Iteration 80 
Iteration 90 
Iteration 100 
Iteration 110 
Iteration 120 
Iteration 130 
Iteration 140 
Iteration 150 
Iteration 160 
Iteration 170 
Iteration 180 
Iteration 190 
Iteration 200 
Sprod test single pseudoimage mode succeeded!
```

The last entries of the sprod_log.txt
```
Retrieving the embedding space...

     user    system   elapsed 
13271.045  3977.321  1010.790 
Warning message:
Lambda may be set too small! 
Saving outputs...

     user    system   elapsed 
13171.555  3944.086  1013.009 
Warning message:
Lambda may be set too small! 
Saving outputs...

15:33:49,ERROR:::Traceback (most recent call last):
15:33:49,ERROR:::  File "/home/mengxiao.he/repositories/SPROD/sprod.py", line 500, in <module>
15:33:49,ERROR:::output_path, os.path.join(output_path, "denoised_stiched.txt")
15:33:49,ERROR:::  File "/home/mengxiao.he/repositories/SPROD/sprod/slide_seq_stiching.py", line 44, in stiching_subsampled_patches
15:33:49,ERROR:::n_barcodes = int(result.split('\n')[-2].split(' ')[4:][0]) - len(patch_cts)
15:33:49,ERROR:::IndexError
15:33:49,ERROR::::
15:33:49,ERROR:::list index out of range
```

Thanks!

**Comment by yunguan-wang** [comment]
Sorry for the late reply. We have fixed the bug. Would you please try again?

**Comment by OliiverHu** [comment]
Hi! I have also tried the test script and still got the exact same error again. 

Here is my log.txt content:

    final  value -28409.928104 
    converged
    Graph construction succeeded.
    
    Number of non-zero edges: 
    Retrieving the embedding space...
    
    final  value -28409.928104 
    converged
    Graph construction succeeded.
    
    Number of non-zero edges: 
         user    system   elapsed 
    11355.874  1470.730   729.123 
    Warning message:
    Lambda may be set too small! 
    Saving outputs...
    
    Retrieving the embedding space...
    
         user    system   elapsed 
    11748.220  1564.160   739.658 
    Warning message:
    Lambda may be set too small! 
    Saving outputs...
    
    23:19:41,ERROR:::Traceback (most recent call last):
    23:19:41,ERROR:::  File "/home/yunfei/SPROD/sprod.py", line 500, in <module>
    23:19:41,ERROR:::output_path, os.path.join(output_path, "denoised_stiched.txt")
    23:19:41,ERROR:::  File "/home/yunfei/SPROD/sprod/slide_seq_stiching.py", line 44, in stiching_subsampled_patches
    23:19:41,ERROR:::n_barcodes = int(result.split('\n')[-2].split(' ')[4:][0]) - len(patch_cts)
    23:19:41,ERROR:::IndexError
    23:19:41,ERROR::::
    23:19:41,ERROR:::list index out of range

**Comment by yunguan-wang** [comment]
Thank you for your testing!
The bug was fixed but last time the push was not complete.
Would you please pull the repo and try again.
Sorry for the inconvenience.

**Comment by OliiverHu** [comment]
Thanks for the reply! I have updated the script and is now testing agian.

**Comment by OliiverHu** [comment]
unfortunately, it still gives error but seems to be a simple one. Would you mind checking that again?

    usage: sprod.py [-h] [--input_type INPUT_TYPE] [--output_prefix OUTPUT_PREFIX]
                    [--sprod_npc SPROD_NPC] [--sprod_umap] [--sprod_R SPROD_R]
                    [--spord_perplexity SPORD_PERPLEXITY]
                    [--sprod_margin SPROD_MARGIN]
                    [--sprod_latent_dim SPROD_LATENT_DIM]
                    [--sprod_graph_reg SPROD_GRAPH_REG]
                    [--sprod_weight_reg SPROD_WEIGHT_REG] [--sprod_diag]
                    [--image_feature_type IMAGE_FEATURE_TYPE] [--warm_start]
                    [--diag_mode] [--num_of_batches NUM_OF_BATCHES] [-ci IMG_TYPE]
                    [--custom_feature CUSTOM_FEATURE]
                    input_path output_path
    sprod.py: error: unrecognized arguments: /home/yunfei/SPROD/test_example/test_output/batch_with_img
    Sprod denoise job failed: no output found, please check sprod_log.txt.

**Comment by yunguan-wang** [comment]
Hi @OliiverHu,
Thank you so much for your feedback.
I realized that the issue was caused by a recent modification of a downstream script used in the 'batch' mode.
I have fixed the cause of the bug and tested locally.
Would you please pull the newest update and try again?
Thanks!
Yunguan

**Comment by OliiverHu** [comment]
The test script works fine now. Thx!
